Parameters:
  ClusterName:
    Type: String
  SecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
  RoleArn:
    Type: String
  KubernetesVersion:
    Type: String
    AllowedValues: 
    - "1.15"
    - "1.14"
    - "1.13"
    Default: "1.15"
    
Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn: !Ref RoleArn
      Version: !Ref KubernetesVersion
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds

Outputs:
  EksArn:
    Value: !GetAtt EKSCluster.Arn
  CAData:
    Value: !GetAtt EKSCluster.CertificateAuthorityData
  EKSEndpoint:
    Value: !GetAtt EKSCluster.Endpoint